"use strict";

// Thin ergonomics layer on top of the NAPI binding.
//
// Purpose:
//   1. Expose CancelError / RetryError that handlers throw to control retries.
//   2. Wrap user handlers in work() so thrown errors are serialized with their
//      full shape (name, message, stack, retry directive) into an envelope the
//      Rust side parses — otherwise Rust only sees the error message string.
//
// The native Queue class comes from ./index.js (generated by NAPI-RS). We
// monkey-patch its `work` prototype method so the wrapping is transparent.

const native = require("./index.js");

const ENVELOPE_PREFIX = "[eddyq:err]";

/**
 * Throw to mark a job permanently failed — the queue will NOT retry,
 * regardless of `maxAttempts`.
 *
 *   throw new CancelError("invalid input — can't recover");
 */
class CancelError extends Error {
  constructor(message = "cancelled") {
    super(message);
    this.name = "CancelError";
    this._eddyqKind = "cancel";
  }
}

/**
 * Throw to retry after a specific delay (milliseconds) instead of the default
 * exponential backoff. Useful for respecting upstream rate-limit headers.
 *
 *   throw new RetryError("rate limited", { delayMs: 60_000 });
 */
class RetryError extends Error {
  constructor(message = "retry", opts = {}) {
    super(message);
    this.name = "RetryError";
    this._eddyqKind = "retry";
    this._eddyqDelayMs = Number(opts.delayMs ?? opts.inMs ?? 0);
  }
}

function formatError(e) {
  if (e instanceof Error) {
    return {
      name: e.name || "Error",
      message: e.message || String(e),
      stack: e.stack,
      directive: e._eddyqKind,
      delayMs: e._eddyqDelayMs,
    };
  }
  if (e && typeof e === "object") {
    return {
      name: e.name || "Error",
      message: e.message || JSON.stringify(e),
      stack: e.stack,
      directive: e._eddyqKind,
      delayMs: e._eddyqDelayMs,
    };
  }
  return { name: "Error", message: String(e) };
}

// Per-Queue instance state: set of in-flight AbortControllers so we can
// `.abort()` all of them when Rust broadcasts a shutdown. A WeakMap keys off
// the instance so multiple Queues in one process don't share aborts.
const instanceState = new WeakMap();

function stateFor(q) {
  let s = instanceState.get(q);
  if (!s) {
    s = { controllers: new Set(), abortRegistered: false };
    instanceState.set(q, s);
  }
  return s;
}

function ensureAbortHandler(q) {
  const s = stateFor(q);
  if (s.abortRegistered) return;
  q.setAbortHandler((reason) => {
    const err = new Error(String(reason ?? "shutdown"));
    err.name = "AbortError";
    for (const c of s.controllers) {
      try {
        c.abort(err);
      } catch {
        // Older AbortController impls don't accept a reason arg.
        try { c.abort(); } catch { /* already aborted */ }
      }
    }
  });
  s.abortRegistered = true;
}

function wrapHandler(handler, q) {
  const s = stateFor(q);
  return async (call) => {
    const controller = new AbortController();
    s.controllers.add(controller);
    const callWithSignal = Object.assign({}, call, { signal: controller.signal });
    try {
      const result = await handler(callWithSignal);
      // JSON has no `undefined` — handlers that don't explicitly return
      // would otherwise round-trip as a rejected promise and trigger a retry.
      return result === undefined ? null : result;
    } catch (e) {
      const envelope = formatError(e);
      // We rethrow a plain Error whose message is our envelope. The Rust
      // dispatcher parses this prefix in crates/eddyq-napi/src/lib.rs::parse_js_failure.
      throw new Error(`${ENVELOPE_PREFIX}${JSON.stringify(envelope)}`);
    } finally {
      s.controllers.delete(controller);
    }
  };
}

// Install the wrapper on Queue's prototype so every instance benefits.
const origWork = native.Eddyq.prototype.work;
native.Eddyq.prototype.work = function work(kind, handler) {
  if (typeof handler !== "function") {
    throw new TypeError("queue.work(kind, handler): handler must be a function");
  }
  ensureAbortHandler(this);
  return origWork.call(this, kind, wrapHandler(handler, this));
};

module.exports = {
  ...native,
  CancelError,
  RetryError,
};
