"use strict";

// Thin ergonomics layer on top of the NAPI binding.
//
// Purpose:
//   1. Expose CancelError / RetryError that handlers throw to control retries.
//   2. Wrap user handlers in work() so thrown errors are serialized with their
//      full shape (name, message, stack, retry directive) into an envelope the
//      Rust side parses — otherwise Rust only sees the error message string.
//
// The native Queue class comes from ./index.js (generated by NAPI-RS). We
// monkey-patch its `work` prototype method so the wrapping is transparent.

const native = require("./index.js");

const ENVELOPE_PREFIX = "[eddyq:err]";

/**
 * Throw to mark a job permanently failed — the queue will NOT retry,
 * regardless of `maxAttempts`.
 *
 *   throw new CancelError("invalid input — can't recover");
 */
class CancelError extends Error {
  constructor(message = "cancelled") {
    super(message);
    this.name = "CancelError";
    this._eddyqKind = "cancel";
  }
}

/**
 * Throw to retry after a specific delay (milliseconds) instead of the default
 * exponential backoff. Useful for respecting upstream rate-limit headers.
 *
 *   throw new RetryError("rate limited", { delayMs: 60_000 });
 */
class RetryError extends Error {
  constructor(message = "retry", opts = {}) {
    super(message);
    this.name = "RetryError";
    this._eddyqKind = "retry";
    this._eddyqDelayMs = Number(opts.delayMs ?? opts.inMs ?? 0);
  }
}

function formatError(e) {
  if (e instanceof Error) {
    return {
      name: e.name || "Error",
      message: e.message || String(e),
      stack: e.stack,
      directive: e._eddyqKind,
      delayMs: e._eddyqDelayMs,
    };
  }
  if (e && typeof e === "object") {
    return {
      name: e.name || "Error",
      message: e.message || JSON.stringify(e),
      stack: e.stack,
      directive: e._eddyqKind,
      delayMs: e._eddyqDelayMs,
    };
  }
  return { name: "Error", message: String(e) };
}

// Per-Queue instance state: set of in-flight AbortControllers so we can
// `.abort()` all of them when Rust broadcasts a shutdown. A WeakMap keys off
// the instance so multiple Queues in one process don't share aborts.
const instanceState = new WeakMap();

function stateFor(q) {
  let s = instanceState.get(q);
  if (!s) {
    // `abortedWith` makes shutdown sticky rather than a one-shot broadcast.
    // The broadcast can only abort controllers that exist when it fires, so a
    // job already claimed in Rust but dispatched into JS a moment later used to
    // build a fresh, never-aborted controller and run its handler to
    // completion. A handler that waits on a signal it will never receive keeps
    // an active libuv timer, and Node cannot exit while one is pending — the
    // process hangs for as long as the handler's own timeout, whatever
    // shutdown mode was requested.
    s = { controllers: new Set(), abortRegistered: false, abortedWith: null };
    instanceState.set(q, s);
  }
  return s;
}

function ensureAbortHandler(q) {
  const s = stateFor(q);
  if (s.abortRegistered) return;
  q.setAbortHandler((reason) => {
    const err = new Error(String(reason ?? "shutdown"));
    err.name = "AbortError";
    // Recorded before the fan-out so anything dispatched from here on refuses
    // to start, rather than racing the loop below.
    s.abortedWith = err;
    for (const c of s.controllers) {
      try {
        c.abort(err);
      } catch {
        // Older AbortController impls don't accept a reason arg.
        try { c.abort(); } catch { /* already aborted */ }
      }
    }
  });
  s.abortRegistered = true;
}

function wrapHandler(handler, q) {
  const s = stateFor(q);
  return async (call) => {
    // Shutdown already broadcast: don't start. Aborting the controller is not
    // enough on its own, because `addEventListener("abort", ...)` on an
    // already-aborted signal never fires — a handler that only listens would
    // still arm its timer and still hold the process open. Refusing outright is
    // also the honest answer: the job has not run, so failing it here lets it
    // be retried by a process that intends to finish it.
    if (s.abortedWith) {
      const envelope = formatError(s.abortedWith);
      throw new Error(`${ENVELOPE_PREFIX}${JSON.stringify(envelope)}`);
    }
    const controller = new AbortController();
    s.controllers.add(controller);
    const callWithSignal = Object.assign({}, call, { signal: controller.signal });
    try {
      const result = await handler(callWithSignal);
      // JSON has no `undefined` — handlers that don't explicitly return
      // would otherwise round-trip as a rejected promise and trigger a retry.
      return result === undefined ? null : result;
    } catch (e) {
      const envelope = formatError(e);
      // We rethrow a plain Error whose message is our envelope. The Rust
      // dispatcher parses this prefix in crates/eddyq-napi/src/lib.rs::parse_js_failure.
      throw new Error(`${ENVELOPE_PREFIX}${JSON.stringify(envelope)}`);
    } finally {
      s.controllers.delete(controller);
    }
  };
}

// Install the wrapper on Queue's prototype so every instance benefits.
const origWork = native.Eddyq.prototype.work;
native.Eddyq.prototype.work = function work(kind, handler) {
  if (typeof handler !== "function") {
    throw new TypeError("queue.work(kind, handler): handler must be a function");
  }
  ensureAbortHandler(this);
  return origWork.call(this, kind, wrapHandler(handler, this));
};

// Same wrapper for the Redis-backed class — keeps the JS-side ergonomics
// (AbortController fan-out, error envelope) identical across backends.
if (native.EddyqRedis && native.EddyqRedis.prototype.work) {
  const origRedisWork = native.EddyqRedis.prototype.work;
  native.EddyqRedis.prototype.work = function work(kind, handler) {
    if (typeof handler !== "function") {
      throw new TypeError("queue.work(kind, handler): handler must be a function");
    }
    ensureAbortHandler(this);
    return origRedisWork.call(this, kind, wrapHandler(handler, this));
  };

}

// Same wrapper for EddyqApp — its `work` registers on both backends, so the
// AbortController fan-out covers handlers running on either backend.
if (native.EddyqApp && native.EddyqApp.prototype.work) {
  const origAppWork = native.EddyqApp.prototype.work;
  native.EddyqApp.prototype.work = function work(kind, handler) {
    if (typeof handler !== "function") {
      throw new TypeError("queue.work(kind, handler): handler must be a function");
    }
    ensureAbortHandler(this);
    return origAppWork.call(this, kind, wrapHandler(handler, this));
  };
}

// BullMQ-style sugar for addSchedule. Accepts:
//   - cron string:     queue.addSchedule(name, "0 */5 * * * *", kind, payload, ...)
//   - object cron:     queue.addSchedule(name, { cron: "..." }, kind, payload, ...)
//   - interval object: queue.addSchedule(name, { every: 300000 }, kind, payload, ...)
// The interval form routes to addIntervalSchedule.
//
// Postgres (`Eddyq`) and Redis (`EddyqRedis`) expose slightly different
// underlying signatures — PG uses an options object for priority/maxAttempts/
// queue, Redis takes them positionally. `applyScheduleSugar` adapts via a
// per-class `callAdd` shim so users see the same JS surface either way.
function applyScheduleSugar(ctor, callAddSchedule, callAddInterval) {
  if (!ctor || !ctor.prototype || !ctor.prototype.addSchedule) return;
  const origAddSchedule = ctor.prototype.addSchedule;
  const origAddInterval = ctor.prototype.addIntervalSchedule;
  ctor.prototype.addSchedule = function addSchedule(
    name,
    when,
    kind,
    payload,
    priority,
    maxAttempts,
    queue,
  ) {
    if (typeof when === "string") {
      return callAddSchedule(origAddSchedule, this, name, when, kind, payload, priority, maxAttempts, queue);
    }
    if (when && typeof when === "object") {
      if (typeof when.every === "number") {
        if (!Number.isFinite(when.every) || when.every <= 0) {
          throw new TypeError("addSchedule: { every } must be a positive number (milliseconds)");
        }
        if (!origAddInterval) {
          throw new TypeError(
            "addSchedule: { every } requires addIntervalSchedule — backend doesn't expose it",
          );
        }
        return callAddInterval(origAddInterval, this, name, when.every, kind, payload, priority, maxAttempts, queue);
      }
      if (typeof when.cron === "string") {
        return callAddSchedule(origAddSchedule, this, name, when.cron, kind, payload, priority, maxAttempts, queue);
      }
    }
    throw new TypeError(
      'addSchedule(name, when, kind, …): `when` must be a cron string, { cron: "…" }, or { every: <ms> }',
    );
  };
}

// Redis: positional priority/maxAttempts/queue on the underlying methods.
applyScheduleSugar(
  native.EddyqRedis,
  (orig, self, name, cron, kind, payload, priority, maxAttempts, queue) =>
    orig.call(self, name, cron, kind, payload, priority, maxAttempts, queue),
  (orig, self, name, every, kind, payload, priority, maxAttempts, queue) =>
    orig.call(self, name, every, kind, payload, priority, maxAttempts, queue),
);

// Postgres: priority/maxAttempts/queue are bundled into an options object.
// Bundle on the way in so users still pass them positionally.
function pgScheduleOptions(priority, maxAttempts, queue) {
  if (priority == null && maxAttempts == null && queue == null) return undefined;
  return { priority, maxAttempts, queue };
}
applyScheduleSugar(
  native.Eddyq,
  (orig, self, name, cron, kind, payload, priority, maxAttempts, queue) =>
    orig.call(self, name, cron, kind, payload, pgScheduleOptions(priority, maxAttempts, queue)),
  (orig, self, name, every, kind, payload, priority, maxAttempts, queue) =>
    orig.call(self, name, every, kind, payload, pgScheduleOptions(priority, maxAttempts, queue)),
);

module.exports = {
  ...native,
  CancelError,
  RetryError,
  // Not public API. The handler wrapper and the shutdown broadcast are plain
  // JS with a genuine ordering hazard between them, and reaching them through
  // the patched prototype requires a live native instance — which is exactly
  // what makes that hazard hard to test. Exposed so it can be exercised
  // directly, deterministically, without a database.
  __internals: { wrapHandler, ensureAbortHandler, stateFor },
};
